-- Banco do OUTBOX (MySQL / MariaDB). O setup.php roda isto sozinho.
CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(190) NOT NULL UNIQUE,
  name VARCHAR(120) NOT NULL DEFAULT '',
  pass_hash VARCHAR(255) NULL,
  is_admin TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS models (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  name VARCHAR(190) NOT NULL,
  data MEDIUMTEXT NOT NULL,
  thumb MEDIUMTEXT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY user_name (user_id, name),
  CONSTRAINT models_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pass_tokens (
  token_hash CHAR(64) PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  expires_at DATETIME NOT NULL,
  CONSTRAINT tokens_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS login_fails (
  k VARCHAR(250) PRIMARY KEY,
  n INT NOT NULL,
  last_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Configurações da equipe (ex.: aba de cada modelo base na galeria).
CREATE TABLE IF NOT EXISTS team_settings (
  k VARCHAR(64) PRIMARY KEY,
  v MEDIUMTEXT NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- HDR / EXR da equipe (luz de foto): o arquivo vai em pedaços para caber nos limites
-- de envio do servidor e do MySQL.
CREATE TABLE IF NOT EXISTS hdr_files (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(190) NOT NULL,
  size INT UNSIGNED NOT NULL,
  chunks INT UNSIGNED NOT NULL,
  complete TINYINT(1) NOT NULL DEFAULT 0,
  user_id INT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS hdr_chunks (
  file_id INT UNSIGNED NOT NULL,
  idx INT UNSIGNED NOT NULL,
  data MEDIUMBLOB NOT NULL,
  PRIMARY KEY (file_id, idx)
) ENGINE=InnoDB;

-- Uploads da equipe (peças STL para reuso na aba Uploads da galeria), em pedaços.
CREATE TABLE IF NOT EXISTS upload_files (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  kind VARCHAR(16) NOT NULL,
  name VARCHAR(190) NOT NULL,
  size INT UNSIGNED NOT NULL,
  chunks INT UNSIGNED NOT NULL,
  thumb MEDIUMTEXT NULL,
  complete TINYINT(1) NOT NULL DEFAULT 0,
  user_id INT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY (kind, name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS upload_chunks (
  file_id INT UNSIGNED NOT NULL,
  idx INT UNSIGNED NOT NULL,
  data MEDIUMBLOB NOT NULL,
  PRIMARY KEY (file_id, idx)
) ENGINE=InnoDB;
